---
- name: Configure Web Server
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: 
          - nginx
        state: present

    - name: Start and enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Create web page
      ansible.builtin.content:
        content: "DevOps Journey is coming along!"
        dest: /var/www/html/index.html 
