name: Deploy Infrastructure and Configure with ansible

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest #GitHub will use the Ubuntu runner to check code

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write public key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
          chmod 644 ~/.ssh/id_ed25519.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init and apply
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve
          terraform output -raw public_ip > ../ansible/inventory

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deployer-key.pem
          chmod 600 ~/.ssh/deployer-key.pem

      - name: Install ansible
        run: |
          sudo apt install -y ansible-core 

      - name: Run ansible playbook
        working-directory: ansible
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory -u ec2-user --private-key ~/.ssh/deployer-key.pem site.yml



